module.exports = {
  userFormateError: {
    code: "10001",
    success: false,
    message: "用户名或密码为空",
    result: "",
  },
  userAlreadyExited: {
    code: "10002",
    success: false,
    message: "用户名已经存在",
    result: "",
  },
  userRegisterError: {
    code: "10003",
    success: false,
    message: "用户注册错误",
    result: "",
  },
  userDoesNotExist: {
    code: "10004",
    success: false,
    message: "用户不存在",
    result: "",
  },
  userLoginError: {
    code: "10005",
    success: false,
    message: "用户登录失败",
    result: "",
  },
  userPasswordError: {
    code: "10006",
    success: false,
    message: "用户密码错误",
    result: "",
  },
  userEditPasswordError: {
    code: "10007",
    success: false,
    message: "更新密码失败",
    result: "",
  },
  tokenExpiredError: {
    code: "10101",
    success: false,
    message: "token过期",
    result: "",
  },
  jsonWebTokenError: {
    code: "10102",
    success: false,
    message: "无效的token",
    result: "",
  },
  isNotAdminError: {
    code: "10103",
    success: false,
    message: "权限错误",
    result: "",
  },
  fileUpLoadError: {
    code: "10201",
    success: false,
    message: "图片上传失败",
    result: "",
  },
  goodsFormateError: {
    code: "10203",
    success: false,
    message: "商品格式错误",
    result: "",
  },
  publishGoodsError: {
    code: "10204",
    success: false,
    message: "上传商品失败",
    result: "",
  },
  updateGoodsError: {
    code: "10205",
    success: false,
    message: "修改商品失败",
    result: "",
  },
  invalidGoodsId: {
    code: "10206",
    success: false,
    message: "商品不存在",
    result: "",
  },
  removeGoodsError: {
    code: "10207",
    success: false,
    message: "删除商品失败",
    result: "",
  },
  restoreGoodsError: {
    code: "10208",
    success: false,
    message: "商品上架失败",
    result: "",
  },
  findAllGoodsError: {
    code: "10209",
    success: false,
    message: "商品查询失败",
    result: "",
  }
}
